server.port=8082
spring.application.name=flight-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/flightdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:flightuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:flightpass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

management.endpoints.web.exposure.include=health,info
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

management.endpoint.health.show-details=always
management.health.db.enabled=true
management.health.kafka.enabled=true
